options(matrixStats.useNames.ifMissing = FALSE)
library(GSVA)
library(GSEABase)
expr<-read.csv("S01-S05.stage-celltype.avr.exp.new",header=T,row.names=1)
AAAP<-read.csv("S01-S05.AAAP.avr.exp",header=T)
AMT<-read.csv("S01-S05.AMT.avr.exp",header=T)
NPF<-read.csv("S01-S05.NPF.avr.exp",header=T)
NRT<-read.csv("S01-S05.NRT.avr.exp",header=T)
UmamiT<-read.csv("S01-S05.UmamiT.avr.exp",header=T)
STP<-read.csv("S01-S05.STP.avr.exp",header=T)
SUC<-read.csv("S01-S05.SUC.avr.exp",header=T)
SWEET<-read.csv("S01-S05.SWEET.avr.exp",header=T)
gene_sets<-list(AAAP=AAAP$Gene,AMT=AMT$Gene,NPF=NPF$Gene,UmamiT=UmamiT$Gene,NRT=NRT$Gene,STP=STP$Gene,SUC=SUC$Gene,SWEET=SWEET$Gene)
gsc <- GeneSetCollection(lapply(names(gene_sets), function(nm) {
GeneSet(gene_sets[[nm]], setName=nm)
}))
library(dplyr)
expr %>% data.frame() %>% mutate(across(where(is.character),as.numeric)) %>% as.matrix() -> expr.new
scores<-gsva(expr=expr.new,gset.idx.list=gsc,method="ssgsea",kcdf="Gaussian",ssgsea.norm=TRUE,verbose=TRUE)
write.csv(scores,file="Rice.S01-S05.CN-related.GSEA.scores.new.csv")